-- 코드를 입력하세요
# SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
# FROM REST_INFO
# WHERE (FOOD_TYPE, FAVORITES) IN
# (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
# FROM REST_INFO
# GROUP BY 1)
# ORDER BY 1 DESC;

# SELECT FOOD_TYPE, REST_ID,  REST_NAME, MAX(FAVORITES) AS FAVORITES
# FROM REST_INFO
# GROUP BY 1
# ORDER BY 4 DESC;

SELECT r1.FOOD_TYPE, r1.REST_ID, r1.REST_NAME, r1.FAVORITES
FROM REST_INFO r1
LEFT JOIN REST_INFO r2
ON r1.FAVORITES < r2.FAVORITES
AND r1.FOOD_TYPE = r2.FOOD_TYPE
WHERE r2.REST_ID IS NULL
ORDER BY r1.FOOD_TYPE DESC