-- 코드를 입력하세요
# SELECT CAR_ID,
#     ROUND(AVG(DATEDIFF(END_DATE, START_DATE)), 1) AVERAGE_DURATION
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE CAR_ID IN (
#     SELECT CAR_ID, 
#         ROUND(AVG(DATEDIFF(END_DATE, START_DATE)), 1)
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE ROUND(AVG(DATEDIFF(END_DATE, START_DATE)), 1) > 6
#     GROUP BY 1
# )
# GROUP BY 1
# ORDER BY 2 DESC, 1 DESC;

# SELECT *
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY

SELECT CAR_ID,
    ROUND(AVG(DATEDIFF(END_DATE, START_DATE)+1), 1) AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY 1
HAVING ROUND(AVG(DATEDIFF(END_DATE, START_DATE)+1), 1) >= 7
ORDER BY 2 DESC, 1 DESC;