-- 코드를 입력하세요
# SELECT USER_ID, NICKNAME, UGB.T AS TOTAL_SALES
# FROM USED_GOODS_USER UGU
# JOIN 
# (SELECT WRITER_ID, SUM(PRICE) AS T
# FROM USED_GOODS_BOARD
# WHERE PRICE >= 700000
# AND STATUS = 'DONE'
# GROUP BY 1) AS UGB
# ON UGU.USER_ID = UGB.WRITER_ID
# ORDER BY 3 ASC;

# SELECT WRITER_ID, SUM(PRICE) AS T, STATUS
# FROM USED_GOODS_BOARD
# WHERE PRICE >= 700000
# AND STATUS = 'DONE'
# GROUP BY 1;

# SELECT *
# FROM USED_GOODS_BOARD;

SELECT U.user_id, U.nickname, SUM(B.price) AS TOTAL_SALES
FROM used_goods_user U
JOIN used_goods_board B ON U.user_id = B.writer_id
WHERE B.status = 'done'
GROUP BY U.user_id, U.nickname
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC;