-- 코드를 입력하세요
# SELECT CATEGORY, PRICE, PRODUCT_NAME
# FROM (SELECT CATEGORY, MAX(PRICE) AS PRICE, PRODUCT_NAME
# FROM FOOD_PRODUCT
# WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
# GROUP BY 1
# ORDER BY 2 DESC
# ) CTE
# ORDER BY PRICE DESC;

# SELECT CATEGORY, MAX(PRICE) AS PRICE
# FROM FOOD_PRODUCT
# WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
# GROUP BY 1
# ORDER BY 2 DESC

# SELECT CATEGORY, PRODUCT_NAME, MAX(PRICE) AS MAX_PRICE
# FROM FOOD_PRODUCT
# GROUP BY 1
# HAVING CATEGORY IN ('과자', '국', '김치', '식용유')
# ORDER BY 3 DESC;

# SELECT CATEGORY, PRICE, PRODUCT_NAME
# FROM FOOD_PRODUCT
# WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
# ORDER BY 2 DESC;

# SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
# FROM FOOD_PRODUCT
# WHERE (CATEGORY, PRICE) IN (
#                             SELECT CATEGORY, MAX(PRICE)
#                             FROM FOOD_PRODUCT
#                             GROUP BY CATEGORY
#                             HAVING CATEGORY IN ('국', '김치', '식용유', '과자')
# )
# ORDER BY MAX_PRICE DESC
# ;

# SELECT * FROM FOOD_PRODUCT ORDER BY PRICE;

SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE) IN (
     SELECT CATEGORY, MAX(PRICE) AS PRICE
     FROM FOOD_PRODUCT
     GROUP BY 1
     HAVING CATEGORY IN ('과자', '국', '김치', '식용유')
     )
ORDER BY 2 DESC;