-- 코드를 입력하세요
SELECT B.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE) TOTAL_SALES
FROM BOOK B
JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE LEFT(SALES_DATE, 7) = '2022-01'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY B.AUTHOR_ID, B.CATEGORY DESC;
# SELECT AUTHOR_ID
# FROM BOOK B JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID;