-- 코드를 입력하세요
SELECT CAR_ID, 
CASE WHEN DATE_FORMAT(END_DATE, '%Y-%m-%d') >= '2022-10-16' THEN '대여중'
ELSE '대여 가능' END AS AVAILABILITY 
FROM 
(SELECT CAR_ID, START_DATE, MAX(END_DATE) AS END_DATE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE, '%Y-%m-%d') < '2022-10-17'
GROUP BY 1) AS TEMP
ORDER BY 1 DESC;