-- 코드를 입력하세요
# SELECT USER_ID, PRODUCT_ID
# FROM (SELECT USER_ID, PRODUCT_ID, row_number() over (partition by USER_ID, PRODUCT_ID ORDER BY USER_ID) AS arn
#       FROM ONLINE_SALE) CTE
# WHERE arn > 1
# ORDER BY USER_ID ASC, PRODUCT_ID DESC;

SELECT DISTINCT user_ID, PRODUCT_ID
FROM ONLINE_SALE
WHERE (user_ID, PRODUCT_ID) IN (
    SELECT user_ID, PRODUCT_ID
    FROM ONLINE_SALE
    GROUP BY user_ID, PRODUCT_ID
    HAVING COUNT(*) > 1
)
ORDER BY user_ID ASC, PRODUCT_ID DESC;